project:
  type: book
  output-dir: docs

book:
  title: "CASA0023-Remotely Sensing"
  author: "Peggy Tsai"
  date: "1/21/2025"
  chapters:
    - index.qmd
    - Week1.qmd
    - about.qmd
    
format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual