project:
  type: website

website:
  title: "PeggyTsai: CASA0023 Remotely Sensing Coursework"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: "Week1"
      href: Week1.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

